import { type AppSettings, ProviderType } from '@/types';

export const createMockSettings = (overrides?: Partial<AppSettings>): AppSettings => ({
  provider: ProviderType.Gemini,
  numAgents: 3,
  model: 'gemini-pro',
  openRouterModel: '',
  activeProfileId: 'default',
  profiles: [{ id: 'default', name: 'Default', initialInstruction: '', refinementInstruction: '', synthesizerInstruction: '' }],
  devMode: false,
  debugMode: false,
  simulateInitialError: 'none',
  simulateRefinementError: 'none',
  simulateSynthesisError: 'none',
  simulateInitialErrorAttempts: 1,
  simulateRefinementErrorAttempts: 1,
  simulateSynthesisErrorAttempts: 1,
  pauseAfterInitial: false,
  pauseAfterRefinement: false,
  useSearchInInitial: true,
  useSearchInRefinement: true,
  useSearchInSynthesis: true,
  temperature: 1.0,
  maxOutputTokens: 8192,
  dynamicAgentRoles: true,
  activeRoleProfileId: 'test-profile',
  roleProfiles: [],
  savedInstructions: [],
  savedRoles: [],
  initialModel: undefined,
  refinementModel: undefined,
  synthesisModel: undefined,
  ...overrides
});
