import { GoogleGenAI, Content, Part, GroundingChunk } from '@google/genai';
import { StepDescriptor, StepContext } from '../../types/steps';
import { AppSettings, AgentState } from '../../types';

const getAgentPerspective = (index: number, settings: AppSettings): { name: string, instruction: string } => {
  const activeRoleProfile = settings.roleProfiles?.find(p => p.id === settings.activeRoleProfileId) || settings.roleProfiles?.[0];
  const perspectives = activeRoleProfile?.roles || [];
  if (perspectives.length === 0) return { name: `Agent ${index + 1}`, instruction: '' };
  return perspectives[index % perspectives.length];
};

export class SynthesisStep implements StepDescriptor {
  id = 'synthesis';
  name = 'Final Synthesis';
  description = 'Synthesizes all refined responses into a final answer.';
  ui = {
    visibleInModal: false, // Synthesis result is the main message text, not shown in "Show Work"
    regenerateLabel: 'Regenerate Final Answer'
  };

  async execute(context: StepContext): Promise<{ text: string; sources?: any[] }> {
    const { ai, settings, history, userInput, image, imageFile, work, onProgress, onMessageUpdate, signal } = context;

    // Ensure we have refined responses
    const refinedResponses = work.results?.['refined'] || work.refinedResponses;
    if (!refinedResponses || refinedResponses.length === 0) {
      throw new Error('Cannot run synthesis step without refined responses');
    }

    // Initialize agent states
    let currentAgentStates: AgentState[] = Array.from({ length: settings.numAgents }, (_, i) => {
      const role = settings.dynamicAgentRoles ? getAgentPerspective(i, settings).name : null;
      return {
        id: `agent-${i}`,
        name: role ? `Agent ${i + 1} (${role})` : `Agent ${i + 1}`,
        status: 'done',
        label: 'Refined'
      };
    });
    currentAgentStates.push({ id: 'synthesizer', name: 'Synthesizer', status: 'working', label: 'Synthesizing...' });
    
    onProgress('Synthesizing final response...', currentAgentStates, work);

    if (settings.devMode) {
      // DEV MODE SIMULATION
      const dummyFinalText = `[DEV MODE] Final Synthesized Answer.\n\nThis is the final output generated by the synthesizer agent in development mode. It combines insights from all ${settings.numAgents} agents into a cohesive response.\n\n1. **Key Insight 1**: Simulation allows for rapid UI testing.\n2. **Key Insight 2**: No API costs are incurred.\n\nConclusion: The system is functioning as expected in development mode.`;
      const words = dummyFinalText.split(' ');
      let finalResponseText = '';
      let isFirstChunk = true;
      
      for (const word of words) {
        if (signal.aborted) throw new Error('Aborted');
        await new Promise(resolve => setTimeout(resolve, 50));
        finalResponseText += word + ' ';
        if (isFirstChunk) {
          onMessageUpdate(finalResponseText, true);
          isFirstChunk = false;
        } else {
          onMessageUpdate(finalResponseText, false);
        }
      }
      
      // Update generic results map
      if (!work.results) work.results = {};
      work.results['synthesis'] = { text: finalResponseText };

      return { text: finalResponseText };

    } else {
      // PROD MODE
      if (!ai) throw new Error("API Key not found");

      const mainChatHistory: Content[] = history.map(msg => ({
        role: msg.role,
        parts: msg.parts,
      }));

      const baseApiParts: Part[] = [];
      if (image) {
        let mimeType = 'image/jpeg';
        if (imageFile) {
          mimeType = imageFile.type;
        } else {
          const match = image.match(/^data:([^;]+);base64,/);
          if (match) mimeType = match[1];
        }
        baseApiParts.push({
          inlineData: {
            mimeType: mimeType,
            data: image.split(',')[1],
          },
        });
      }
      if (userInput.trim()) {
        baseApiParts.push({ text: userInput });
      }

      const synthesizerContext = `Here are the ${settings.numAgents} refined responses to the user's query. Your task is to synthesize them into the best single, final answer. \n\n${refinedResponses.map((answer: string, i: number) => `Refined Response ${i + 1}:\n"${answer}"`).join('\n\n')}`;
      const synthesizerTurn: Content = { role: 'user', parts: [...baseApiParts, {text: `\n\n---INTERNAL CONTEXT---\n${synthesizerContext}`}] };
      
      const activeProfile = settings.profiles.find(p => p.id === settings.activeProfileId) || settings.profiles[0];
      
      const stream = await ai.models.generateContentStream({
        model: settings.model,
        contents: [...mainChatHistory, synthesizerTurn],
        config: {
          systemInstruction: activeProfile.synthesizerInstruction,
          temperature: settings.temperature ?? 0.7,
          tools: [{googleSearch: {}}],
          thinkingConfig: { thinkingBudget: settings.model.includes('flash') ? 24576 : 32768 },
          maxOutputTokens: 65536,
        },
      });

      let finalResponseText = '';
      const allGroundingChunks: GroundingChunk[] = [];
      let isFirstChunk = true;
 
      for await (const chunk of stream) {
        if (signal.aborted) throw new Error('Aborted');
        finalResponseText += chunk.text;
        const groundingChunks = chunk.candidates?.[0]?.groundingMetadata?.groundingChunks;
        if (groundingChunks) {
            allGroundingChunks.push(...groundingChunks);
        }
        if (isFirstChunk) {
          onMessageUpdate(finalResponseText, true);
          isFirstChunk = false;
        } else {
          onMessageUpdate(finalResponseText, false);
        }
      }

      const sources = allGroundingChunks
        .map((chunk) => chunk.web)
        .filter((web): web is { uri: string; title: string; } => !!web && !!web.uri)
        .filter((web, index, self) => index === self.findIndex(w => w.uri === web.uri));

      // Update generic results map
      if (!work.results) work.results = {};
      work.results['synthesis'] = { text: finalResponseText, sources };

      return { text: finalResponseText, sources };
    }
  }
}