import { GoogleGenAI, Content, Part, GroundingChunk } from '@google/genai';
import { StepDescriptor, StepContext } from '../../types/steps';
import { AppSettings, AgentState } from '../../types';
import { prepareGeminiContent } from '../contentUtils';
import { getGenerationConfig } from '../geminiConfig';

const getAgentPerspective = (index: number, settings: AppSettings): { name: string, instruction: string } => {
  const activeRoleProfile = settings.roleProfiles?.find(p => p.id === settings.activeRoleProfileId) || settings.roleProfiles?.[0];
  const perspectives = activeRoleProfile?.roles || [];
  if (perspectives.length === 0) return { name: `Agent ${index + 1}`, instruction: '' };
  return perspectives[index % perspectives.length];
};

export class SynthesisStep implements StepDescriptor {
  id = 'synthesis';
  name = 'Final Synthesis';
  description = 'Synthesizes all refined responses into a final answer.';
  ui = {
    visibleInModal: false, // Synthesis result is the main message text, not shown in "Show Work"
    regenerateLabel: 'Regenerate Final Answer'
  };

  async execute(context: StepContext): Promise<{ text: string; sources?: any[] }> {
    const { ai, settings, history, userInput, image, imageFile, work, onProgress, onMessageUpdate, signal } = context;

    // Ensure we have refined responses
    const refinedResponses = work.results?.['refined'] || work.refinedResponses;
    if (!refinedResponses || refinedResponses.length === 0) {
      throw new Error('Cannot run synthesis step without refined responses');
    }

    // Initialize agent states
    let currentAgentStates: AgentState[] = Array.from({ length: settings.numAgents }, (_, i) => {
      const role = settings.dynamicAgentRoles ? getAgentPerspective(i, settings).name : null;
      return {
        id: `agent-${i}`,
        name: role ? `Agent ${i + 1} (${role})` : `Agent ${i + 1}`,
        status: 'done',
        label: 'Refined'
      };
    });
    currentAgentStates.push({ id: 'synthesizer', name: 'Synthesizer', status: 'working', label: 'Synthesizing...' });
    
    onProgress('Synthesizing final response...', currentAgentStates, work);

    if (settings.devMode) {
      // DEV MODE SIMULATION
      const dummyFinalText = `[DEV MODE] Final Synthesized Answer.\n\nThis is the final output generated by the synthesizer agent in development mode. It combines insights from all ${settings.numAgents} agents into a cohesive response.\n\n1. **Key Insight 1**: Simulation allows for rapid UI testing.\n2. **Key Insight 2**: No API costs are incurred.\n\nConclusion: The system is functioning as expected in development mode.`;
      const words = dummyFinalText.split(' ');
      let finalResponseText = '';
      let isFirstChunk = true;
      
      for (const word of words) {
        if (signal.aborted) throw new Error('Aborted');
        await new Promise(resolve => setTimeout(resolve, 50));
        finalResponseText += word + ' ';
        if (isFirstChunk) {
          onMessageUpdate(finalResponseText, true);
          isFirstChunk = false;
        } else {
          onMessageUpdate(finalResponseText, false);
        }
      }
      
      // Update generic results map
      if (!work.results) work.results = {};
      work.results['synthesis'] = { text: finalResponseText };

      // Mark synthesizer as completed in agent states
      currentAgentStates = currentAgentStates.map(a =>
        a.id === 'synthesizer'
          ? { ...a, status: 'done', label: 'Synthesized' }
          : a
      );
      onProgress('Synthesis completed', currentAgentStates, work);

      return { text: finalResponseText };

    } else {
      // PROD MODE
      if (!ai) throw new Error("API Key not found");

      const { history: mainChatHistory, baseApiParts } = prepareGeminiContent(history, userInput, image, imageFile);

      const agentDrafts = refinedResponses
        .map((answer: string, i: number) => `    <draft id="agent_${i + 1}">\n${answer}\n    </draft>`)
        .join('\n\n');

      const synthesizerContext = `
# INPUT DATA
<context_data>
<original_query>
${userInput || "(See attached image/content)"}
</original_query>

<agent_drafts>
${agentDrafts}
</agent_drafts>
</context_data>

# YOUR TASK
<instruction>
As defined in <mission> synthesize the best single, final answer from <agent_drafts> to address <original_query>.
1. Resolve any contradictions.
2. [CRITICAL] Combine the best insights.
3. Structure the response clearly.
4. [CRITICAL] You MUST ALWAYS use the googleSearch tool to verify facts and find additional information if needed!
</instruction>`;

      const synthesizerTurn: Content = { role: 'user', parts: [...baseApiParts, {text: `\n\n---INTERNAL CONTEXT---\n${synthesizerContext}`}] };
      
      const activeProfile = settings.profiles.find(p => p.id === settings.activeProfileId) || settings.profiles[0];
      const systemInstruction = `<system_instruction>\n# SYSTEM INSTRUCTION\n<mission>${activeProfile.synthesizerInstruction}</mission>\n</system_instruction>`;
      
      try {
        // Capture debug info
        if (!work.debugInfo) work.debugInfo = {};
        work.debugInfo['synthesis'] = {
            systemInstruction,
            history: mainChatHistory,
            userTurn: synthesizerTurn
        };

        const stream = await ai.models.generateContentStream({
          model: settings.model,
          contents: [...mainChatHistory, synthesizerTurn],
          config: {
            ...getGenerationConfig(settings.model, settings.temperature, settings.unsafeTemperature),
            systemInstruction,
            tools: [{googleSearch: {}}],
          },
        });

        let finalResponseText = '';
        const allGroundingChunks: GroundingChunk[] = [];
        let isFirstChunk = true;
  
        for await (const chunk of stream) {
          if (signal.aborted) throw new Error('Aborted');
          finalResponseText += chunk.text;
          const groundingChunks = chunk.candidates?.[0]?.groundingMetadata?.groundingChunks;
          if (groundingChunks) {
              allGroundingChunks.push(...groundingChunks);
          }
          if (isFirstChunk) {
            onMessageUpdate(finalResponseText, true);
            isFirstChunk = false;
          } else {
            onMessageUpdate(finalResponseText, false);
          }
        }

        const sources = allGroundingChunks
          .map((chunk) => chunk.web)
          .filter((web): web is { uri: string; title: string; } => !!web && !!web.uri)
          .filter((web, index, self) => index === self.findIndex(w => w.uri === web.uri));

        // Update generic results map
        if (!work.results) work.results = {};
        work.results['synthesis'] = { text: finalResponseText, sources };

        // Mark synthesizer as completed in agent states
        currentAgentStates = currentAgentStates.map(a =>
          a.id === 'synthesizer'
            ? { ...a, status: 'done', label: 'Synthesized' }
            : a
        );
        onProgress('Synthesis completed', currentAgentStates, work);

        return { text: finalResponseText, sources };
      } catch (error) {
        console.error('Synthesis failed:', error);
        currentAgentStates = currentAgentStates.map(a => a.id === 'synthesizer' ? { ...a, status: 'error', label: 'Synthesis Failed' } : a);
        onProgress('Synthesis failed', currentAgentStates, work);
        throw error;
      }
    }
  }

  async regenerate(context: StepContext): Promise<{ text: string; sources?: any[] }> {
    return this.execute(context);
  }
}