import { StepId, STEPS } from '@/types';

export const DEV_MODE_DURATIONS = {
  [STEPS.INITIAL]: 10000,
  [STEPS.REFINEMENT]: 100,
  [STEPS.SYNTHESIS]: 2000
} as const;

/**
 * Simulates streaming text word by word.
 */
export const simulateStreaming = async (
  text: string,
  options: {
    totalDurationMs?: number;
    signal: AbortSignal;
    onChunk: (currentText: string) => void;
  }
): Promise<string> => {
  const { totalDurationMs = 2000, signal, onChunk } = options;
  const words = text.split(' ');
  const delayPerWord = totalDurationMs / words.length;
  let currentText = '';

  for (const word of words) {
    if (signal.aborted) throw new Error('Aborted');
    await new Promise(resolve => setTimeout(resolve, delayPerWord));
    currentText += word + ' ';
    onChunk(currentText);
  }

  return currentText.trim();
};

/**
 * Generates dev mode dummy text for each step type.
 */
export const getDevModeText = (step: StepId, agentIndex?: number): string => {
  switch (step) {
    case STEPS.INITIAL:
      return `[DEV MODE] Initial draft from Agent ${(agentIndex ?? 0) + 1}. This is a simulated response designed to take exactly 10 seconds. We are testing the timer functionality to ensure that the UI handles long-running processes correctly. This text is being streamed word by word to mimic the behavior of a real LLM generation. 1... 2... 3... 4... 5...`;
    case STEPS.REFINEMENT:
      return `[DEV MODE] Refined response from Critic ${(agentIndex ?? 0) + 1}. Critiquing the initial draft.`;
    case STEPS.SYNTHESIS:
      return `[DEV MODE] Final Synthesized Answer.\n\nThis is the final output generated by the synthesizer agent in development mode. It combines insights from all agents into a cohesive response.\n\n1. **Key Insight 1**: Simulation allows for rapid UI testing.\n2. **Key Insight 2**: No API costs are incurred.\n\nConclusion: The system is functioning as expected in development mode.`;
  }
};
